import frappe
import json
from phoenix_pharma.phoenix_pharma.custom.helper import (
    load_exploded_se_items,
    update_exploded_items_in_work_order,
    load_issued_items_from_work_order,
)
from phoenix_pharma.phoenix_pharma.utils.control_number import (
    update_control_number_from_exploded_items,
)
from phoenix_pharma.phoenix_pharma.utils.utils import (
    get_env_prefix,
    send_notification,
)
from phoenix_pharma.phoenix_pharma.utils.api_purity_utils import apply_purity_adjustment


def before_insert(doc, method=None):
    if doc.amended_from:
        doc.custom_notified_statuses = json.dumps(
            [
                "Pending Quality Review",
                "Pending QA Review",
                # "Pending Stores Review",     #* Removed the pending stores review from stock entry as its not needed anymore
                "Approved",
            ]
        )
    
    if doc.stock_entry_type == "Manufacture":
        doc.inspection_required = 1

def on_update(doc, method=None):
    if doc.stock_entry_type != "Manufacture":
        return  # Only trigger for Manufacture type

    # Load notified statuses from custom field
    notified_statuses = []
    if doc.custom_notified_statuses:
        try:
            notified_statuses = json.loads(doc.custom_notified_statuses)
        except Exception:
            pass  # Ignore malformed JSON

    current_status = doc.workflow_state
    if current_status not in notified_statuses:
        return  # Status already notified

    if not doc.custom_cost_center:
        frappe.throw(
            "Cost Center is mandatory to send notifications in stock entry. Please set the Cost Center before proceeding, else contact support"
        )
    # Get Sales Order from Work Order (if available)
    sales_order = None
    if doc.work_order:
        sales_order = frappe.db.get_value("Work Order", doc.work_order, "sales_order")
        sales_order_link = (
            frappe.utils.get_url_to_form("Sales Order", sales_order)
            if sales_order
            else None
        )
        stock_entry_link = frappe.utils.get_url_to_form("Stock Entry", doc.name)
        cost_center = doc.custom_cost_center

    fg_item_code = None
    fg_item_name = None
    fg_warehouse = None
    for item in doc.items:
        if item.is_finished_item == 1:
            fg_item_code = item.item_code
            fg_item_name = item.item_name
            fg_warehouse = item.t_warehouse

    if not fg_item_code:
        frappe.throw(
            "Finished Item not found in Stock Entry, recheck the items table as per correct format else contact support"
        )

    if not fg_warehouse:
        frappe.throw(
            "FG / SFG warehouse not found in Stock Entry, recheck the items table as per correct format else contact support"
        )
    
    # warehouse_type check for billing notif.
    warehouse_type = frappe.db.get_value("Warehouse", fg_warehouse, "warehouse_type")

    qa_role_map = {
        "Puducherry - PBPL": "QA Approver Puducherry - PBPL",
        "Assam - PBPL": "QA Approver Assam - PBPL",
        "Assam - PL": "QA Approver Assam - PL",
    }

    qc_role_map = {
        "Puducherry - PBPL": "QC Approver Puducherry - PBPL",
        "Assam - PBPL": "QC Approver Assam - PBPL",
        "Assam - PL": "QC Approver Assam - PL",
    }

    stores_role_map = {
        "Puducherry - PBPL": "Stores Approver Puducherry - PBPL",
        "Assam - PBPL": "Stores Approver Assam - PBPL",
        "Assam - PL": "Stores Approver Assam - PL",
    }

    if doc.workflow_state == "Pending Quality Review":
        qc_role = qc_role_map.get(cost_center)
        # Notify QC
        if qc_role:
            qc_subject = f"{get_env_prefix()} QC [Action]: QC Tests needed for Manufacture Stock Entry {doc.name}"
            qc_message = (
                f"Hello QC Team,<br>"
                f"Please raise Quality Inspection and generate FP COA for stock entry type Manufacture.<br>"
                f"<b>Stock Entry:</b> <a href='{stock_entry_link}' target='_blank'>{doc.name}</a><br>"
                f"<b>Status:</b> {doc.workflow_state}<br>"
                f"<b>Item:</b> {fg_item_code}: {fg_item_name}<br>"
                f"<b>Batch:</b> {doc.custom_batch_no}<br>"
                f"<b>Sales Order URL:</b> <a href='{sales_order_link}' target='_blank'>{sales_order}</a><br>"
            )
            send_notification(doc, qc_role, qc_subject, qc_message)

    if doc.workflow_state == "Pending QA Review":
        qa_role = qa_role_map.get(cost_center)
        # Notify QA Users
        if qa_role:
            qa_subject = f"{get_env_prefix()} QA [Action]: Stock Entry Type Manufacture {doc.name}, Please approve this request after reviewing."
            qa_message = (
                f"Hello QA Team,<br>"
                f"Please verify if FP or SFP COA is generated by QC team & other details and move this request to issue / move the batch to FG / SFG stores.<br>"
                f"<b>Stock Entry:</b> <a href='{stock_entry_link}' target='_blank'>{doc.name}</a><br>"
                f"<b>Status:</b> {doc.workflow_state}<br>"
                f"<b>Item:</b> {fg_item_code}: {fg_item_name}<br>"
                f"<b>Batch:</b> {doc.custom_batch_no}<br>"
                f"<b>Warehouse:</b> {fg_warehouse}<br>"
                f"<b>Sales Order URL:</b> <a href='{sales_order_link}' target='_blank'>{sales_order}</a><br>"
            )
            send_notification(doc, qa_role, qa_subject, qa_message)

    if doc.workflow_state == "Approved" and warehouse_type == "Billing":
        stores_role = stores_role_map.get(cost_center)
        # Notify Stores Users on submission
        if stores_role:
            stores_subject = f"{get_env_prefix()} Stores [Action]: Stock Entry Type Manufacture {doc.name}, Finished Product transferred to FG warehouse & proceed for billing"
            stores_message = (
                f"Hello Stores Team,<br>"
                f"The Batch is ready for billing with qty mentioned in the Manufacture type stock entry, Please proceed with logistics & billing.<br>"
                f"<b>Stock Entry:</b> <a href='{stock_entry_link}' target='_blank'>{doc.name}</a><br>"
                f"<b>Status:</b> {doc.workflow_state}<br>"
                f"<b>Item:</b> {fg_item_code}: {fg_item_name}<br>"
                f"<b>Batch:</b> {doc.custom_batch_no}<br>"
                f"<b>FG Warehouse:</b> {fg_warehouse}<br>"
                f"<b>Sales Order URL:</b> <a href='{sales_order_link}' target='_blank'>{sales_order}</a><br>"
            )
            send_notification(doc, stores_role, stores_subject, stores_message)

    # After sending notifications
    if current_status in notified_statuses:
        notified_statuses.remove(current_status)
        doc.db_set(
            "custom_notified_statuses",
            json.dumps(notified_statuses),
            update_modified=False,
        )


# call the method which will load the exploded items table in stock entry based on the batch and qty
def before_validate(doc, method=None):
    # If manual selection is ON, skip auto loading
    if doc.get("custom_select_arn_manually"):
        return
    # * check if it is not is_return and stock entry type material transfer for manufacture,
    # * return_to_store_from_production_wip = doc.is_return and doc.stock_entry_type == "Material Transfer for Manufacture"
    # * else if it is other fn to fetch from the work order based on the item and batch if available from issued qty child table
    # * do not load the exploded table in stock entry type manufacture, at the customize form level add it and code level to if possible
    return_to_store_from_production_wip = (
        doc.is_return and doc.stock_entry_type == "Material Transfer for Manufacture"
    )
    if not return_to_store_from_production_wip:
        load_exploded_se_items(doc)
    else:
        load_issued_items_from_work_order(doc)

    # Apply API purity adjustment AFTER ARN items are loaded
    # Only for forward (non-return) manufacture entries
    if not doc.is_return:
        apply_purity_adjustment(doc)


def on_submit(doc, method):
    # reduce the qty of CN on submit from exploded items table
    update_control_number_from_exploded_items(doc, reverse=False)
    update_exploded_items_in_work_order(doc)


def on_cancel(doc, method):
    # adds the qty of CN on cancel into exploded items table
    update_control_number_from_exploded_items(doc, reverse=True)
    update_exploded_items_in_work_order(doc)
